### ISSUE TITLE
タブ周りのデザイン変更案

### ISSUE THREAD

**Issue by hashrock** [hashrock/DevHub#1]
Material Design風にできないか？

現行版

![c3fhcjnarx](https://cloud.githubusercontent.com/assets/3132889/8400996/fe7cebfe-1e62-11e5-9332-4a376b26847e.gif)

ボックスシャドウあり

![cyi3i394ib](https://cloud.githubusercontent.com/assets/3132889/8400979/bed36eec-1e62-11e5-9949-a57fea1c4f78.gif)

ボックスシャドウなし

![anukokvtcv](https://cloud.githubusercontent.com/assets/3132889/8400981/c357d08e-1e62-11e5-89a5-6986e4dc0776.gif)

**Comment by hashrock** [comment]
ぱっと見の視認性は、一番上がいいのだけれど…

**Comment by volpe28v** [comment]
確かに既存のTwitterBootstrapのが選択済みのがわかりやすいですが、
2番目のもオシャレでかっこいいですね。

**Comment by hashrock** [comment]
お疲れ様です！もう見つかってしまいましたか…笑
PR出せそうなアイデアをここに溜めていこうと思ってます。
採用すると良さそうなものがあれば言って頂けるとありがたいです！

**Comment by volpe28v** [comment]
見つけちゃいましたｗ
自分では思いつかないデザインを見るのとても楽しいです！
気になったらコメントさせていただきますねー。

※cssだいぶ散らかってるので微調整とか大変なのが申し訳ないです。。。
　あと、fork したリポジトリにも issue 作れるんですね。発見でした。

**Comment by volpe28v** [comment]
タブのデザイン変えたくなったので参考にさせていただきました！(上バーにしてみました)

**Comment by hashrock** [comment]
取り入れていただきありがとうございます！
